- name: configure rabbitmq server 
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install rabbitmq server
    ansible.builtin.dnf:
     name: rabbitmq-server
     state: present

  - name: Enable and start rabbitmq service
    ansible.builtin.service:
     name: rabbitmq-server   
     enabled: yes
     state: restarted 

  - name: Add user and set password
    community.rabbitmq.rabbitmq_user:
     user: roboshop 
     password: roboshop123
     permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
     state: present

    # ansible-playbook -i inventory.ini rabbitmq.yaml to run the script
